name: sccache MVP

on: push

jobs:
  build:
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: "sccache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.8
        with:
          version: "v0.10.0"

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo build
